modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/EliotWL/MysticalWildlife/issues"

[[mods]]
modId="mysticalwildlife"
version="1.0.0.0"
displayName="Mystical Wildlife 1.15.2 Fork"
displayURL=""
logoFile="logo.png"
authors="EliotWL with credit to original authors Lykrast, MCVinnyq"
description='''
Fork of Lykrast's mod the adds several imaginary animals to populate your worlds and make the wildlife a bit more varied and interesting, especially from biome to biome.  Now ported to 1.15.2
'''



[[dependencies.mysticalwildlife]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mysticalwildlife]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"